// Code generated by tools/genprims.vsh from vlib/math at V 0.5.2 abcebfc.
// DO NOT EDIT: rerun `v run tools/genprims.vsh` instead.
// Wired into the table by one line in table(): register_gen_math(mut p).
module prims

import math
import vlib.blip
import vlib.blip.printer

// math-cos wraps math.cos(x f64) f64.
fn prim_gen_math_cos(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-cos expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-cos expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.cos(a0))
}

// math-exp wraps math.exp(x f64) f64.
fn prim_gen_math_exp(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-exp expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-exp expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.exp(a0))
}

// math-factorial wraps math.factorial(n f64) f64.
fn prim_gen_math_factorial(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-factorial expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-factorial expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.factorial(a0))
}

// math-floor wraps math.floor(x f64) f64.
fn prim_gen_math_floor(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-floor expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-floor expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.floor(a0))
}

// math-log wraps math.log(a f64) f64.
fn prim_gen_math_log(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-log expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-log expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.log(a0))
}

// math-log10 wraps math.log10(x f64) f64.
fn prim_gen_math_log10(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-log10 expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-log10 expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.log10(a0))
}

// math-log2 wraps math.log2(x f64) f64.
fn prim_gen_math_log2(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-log2 expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-log2 expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.log2(a0))
}

// math-sin wraps math.sin(x f64) f64.
fn prim_gen_math_sin(args []blip.Value) !blip.Value {
	if args.len != 1 {
		return error('math-sin expects 1 argument(s), got ${args.len}')
	}
	a0 := as_f64(args[0]) or { return error('math-sin expects a number, got ${printer.write(args[0])}') }
	return blip.float(math.sin(a0))
}

fn register_gen_math(mut p map[string]blip.PrimFn) {
	p['math-cos'] = prim_gen_math_cos
	p['math-exp'] = prim_gen_math_exp
	p['math-factorial'] = prim_gen_math_factorial
	p['math-floor'] = prim_gen_math_floor
	p['math-log'] = prim_gen_math_log
	p['math-log10'] = prim_gen_math_log10
	p['math-log2'] = prim_gen_math_log2
	p['math-sin'] = prim_gen_math_sin
}
