module main

/* sitegen builds the vlip website.
 *
 * Written in V on purpose: the project's stated final phase is a website
 * generated by vlip, and doing it in the language the site is about is the
 * cheapest possible rehearsal of that. It also forces the generator to be a real
 * program rather than a pile of templates.
 *
 * Layout on disk:
 *
 *   site/content/       not used; the page structure lives below, in V
 *   site/i18n/<code>.json   flat {"key": "text"} per language
 *   site/assets/        style.css, site.js
 *   site_out/           generated; what GitHub Pages deploys
 *
 * Strings live in JSON and are FLAT on purpose: a flat string map is the one
 * shape V's json decoder handles without surprises. Page structure is V data.
 *
 * Translation fallback: any key a language does not define falls back to
 * English, and the affected block is marked as untranslated. A partially
 * translated page says so rather than quietly mixing two languages without
 * telling the reader.
 */

import os
import json2

// ---------------------------------------------------------------- content ---

// site_root is the address GitHub Pages serves this site from. It appears in
// exactly one place -- the hreflang alternate links -- because those are the only
// URLs on the page that must be absolute. Everything else is relative, so the
// site still works from a file:// path or a different mount point.
const site_root = 'https://metif12.github.io/vlip'

struct Lang {
	code string
	name string
	dir  string // 'ltr' or 'rtl'
}

struct Item {
	title string
	body  string
	code  string
}

struct Section {
	kind    string // hero | cards | table | code | prose | steps | callout
	title   string
	sub     string
	items   []Item
	cols    []string
	rows    [][]string
	code    string
	body    []string
	tone    string
	note    string
}

struct Page {
	id    string
	url   string
	nav   string
	depth int
	secs  []Section
}

fn langs() []Lang {
	return [
		Lang{'en', 'English', 'ltr'},
		Lang{'fa', 'فارسی', 'rtl'},
		Lang{'ar', 'العربية', 'rtl'},
		Lang{'es', 'Español', 'ltr'},
		Lang{'fr', 'Français', 'ltr'},
		Lang{'de', 'Deutsch', 'ltr'},
		Lang{'pt', 'Português', 'ltr'},
		Lang{'ru', 'Русский', 'ltr'},
		Lang{'uk', 'Українська', 'ltr'},
		Lang{'pl', 'Polski', 'ltr'},
		Lang{'nl', 'Nederlands', 'ltr'},
		Lang{'tr', 'Türkçe', 'ltr'},
		Lang{'hi', 'हिन्दी', 'ltr'},
		Lang{'zh', '简体中文', 'ltr'},
		Lang{'ja', '日本語', 'ltr'},
		Lang{'ko', '한국어', 'ltr'},
	]
}

fn pages() []Page {
	return [
		Page{
			id:    'home'
			url:   ''
			nav:   'nav.home'
			depth: 0
			secs: [
				Section{
					kind: 'hero'
					title: 'home.title'
					sub:   'home.sub'
				},
				Section{
					kind: 'code'
					title: 'home.taste'
					code:  '(define (fib n)\n  (if (< n 2)\n      n\n      (+ (fib (- n 1))\n         (fib (- n 2)))))\n\n(fib 20)          ;=> 6765'
				},
				Section{
					kind:  'cards'
					title: 'home.pillars'
					items: [
						Item{'home.p1.t', 'home.p1.b', ''},
						Item{'home.p2.t', 'home.p2.b', ''},
						Item{'home.p3.t', 'home.p3.b', ''},
					]
				},
				Section{
					kind: 'callout'
					tone: 'note'
					title: 'home.statusTitle'
					body:  ['home.status1', 'home.status2']
				},
			]
		},
		Page{
			id:    'features'
			url:   'features/'
			nav:   'nav.features'
			depth: 1
			secs: [
				Section{
					kind: 'hero'
					title: 'features.title'
					sub:   'features.sub'
				},
				Section{
					kind:  'cards'
					title: 'features.what'
					items: [
						Item{'features.tco.t', 'features.tco.b', ''},
						Item{'features.machine.t', 'features.machine.b', ''},
						Item{'features.truthy.t', 'features.truthy.b', ''},
						Item{'features.forms.t', 'features.forms.b', ''},
						Item{'features.errors.t', 'features.errors.b', ''},
						Item{'features.embed.t', 'features.embed.b', ''},
					]
				},
				Section{
					kind: 'prose'
					title: 'features.depth'
					body: ['features.depth1', 'features.depth2']
				},
				Section{
					kind: 'table'
					title: 'features.benchTitle'
					cols: ['features.bench1', 'features.bench2',
						'features.bench3', 'features.bench4']
					rows: [
						['features.b1', '250,000', '250000', '0'],
						['features.b2', '20,000', 'pong', '0'],
						['features.b3', '100,000', '100000', '0'],
						['features.b4', '50,000', '50000', '0'],
						['features.b5', '20', '6765', '0'],
						['features.b6', '20,000', '199990000', '0'],
					]
				},
				Section{
					kind: 'callout'
					tone: 'note'
					title: 'features.benchNoteT'
					body:  ['features.benchNote']
				},
			]
		},
		Page{
			id:    'docs'
			url:   'docs/'
			nav:   'nav.docs'
			depth: 1
			secs: [
				Section{
					kind: 'hero'
					title: 'docs.title'
					sub:   'docs.sub'
				},
				Section{
					kind: 'table'
					title: 'docs.values'
					cols: ['docs.v1', 'docs.v2', 'docs.v3']
					rows: [
						['docs.val.nil', 'docs.val.nil.d', 'docs.val.nil.e'],
						['docs.val.bool', 'docs.val.bool.d', 'docs.val.bool.e'],
						['docs.val.int', 'docs.val.int.d', 'docs.val.int.e'],
						['docs.val.float', 'docs.val.float.d', 'docs.val.float.e'],
						['docs.val.rune', 'docs.val.rune.d', 'docs.val.rune.e'],
						['docs.val.string', 'docs.val.string.d', 'docs.val.string.e'],
						['docs.val.sym', 'docs.val.sym.d', 'docs.val.sym.e'],
						['docs.val.kw', 'docs.val.kw.d', 'docs.val.kw.e'],
						['docs.val.list', 'docs.val.list.d', 'docs.val.list.e'],
						['docs.val.vec', 'docs.val.vec.d', 'docs.val.vec.e'],
						['docs.val.table', 'docs.val.table.d', 'docs.val.table.e'],
						['docs.val.array', 'docs.val.array.d', 'docs.val.array.e'],
						['docs.val.closure', 'docs.val.closure.d',
							'docs.val.closure.e'],
						['docs.val.prim', 'docs.val.prim.d', 'docs.val.prim.e'],
					]
				},
				Section{
					kind: 'table'
					title: 'docs.core'
					cols: ['docs.c1', 'docs.c2', 'docs.c3']
					rows: [
						['docs.core.if', 'docs.core.if.d', '`if`'],
						['docs.core.define', 'docs.core.define.d',
							'`define`'],
						['docs.core.set', 'docs.core.set.d', '`set!`'],
						['docs.core.lambda', 'docs.core.lambda.d',
							'`lambda`, `fn`'],
						['docs.core.begin', 'docs.core.begin.d', '`begin`'],
						['docs.core.let', 'docs.core.let.d',
							'`let`, `let*`, `letrec`'],
						['docs.core.and', 'docs.core.and.d', '`and`, `or`'],
						['docs.core.quote', 'docs.core.quote.d', '`quote`'],
					]
				},
				Section{
					kind: 'table'
					title: 'docs.derived'
					cols: ['docs.c1', 'docs.c2', 'docs.c3']
					rows: [
						['docs.der.when', 'docs.der.when.d', '`if`'],
						['docs.der.unless', 'docs.der.unless.d', '`if`'],
						['docs.der.cond', 'docs.der.cond.d', 'nested `if`'],
						['docs.der.case', 'docs.der.case.d', '`cond`'],
						['docs.der.loop', 'docs.der.loop.d', 'named `let`'],
						['docs.der.dotimes', 'docs.der.dotimes.d', '`loop`'],
					]
				},
				Section{
					kind: 'prose'
					title: 'docs.truthyTitle'
					body: ['docs.truthy1', 'docs.truthy2']
				},
				Section{
					kind: 'table'
					title: 'docs.prims'
					cols: ['docs.c1', 'docs.c2', 'docs.c3']
					rows: [
						['docs.p.arith', 'docs.p.arith.d',
							'`+` `-` `*` `/` `%`'],
						['docs.p.cmp', 'docs.p.cmp.d', '`=` `<` `>` `<=` `>=`'],
						['docs.p.logic', 'docs.p.logic.d', '`not`'],
						['docs.p.list', 'docs.p.list.d',
							'`car` `cdr` `cons` `list` `null?`'],
						['docs.p.seq', 'docs.p.seq.d',
							'`map` `filter` `fold` `apply`'],
						['docs.p.io', 'docs.p.io.d', '`print` `println`'],
					]
				},
				Section{
					kind: 'callout'
					tone: 'warn'
					title: 'docs.wipTitle'
					body:  ['docs.wip1', 'docs.wip2']
				},
			]
		},
		Page{
			id:    'guides'
			url:   'guides/'
			nav:   'nav.guides'
			depth: 1
			secs: [
				Section{
					kind: 'hero'
					title: 'guides.title'
					sub:   'guides.sub'
				},
				Section{
					kind: 'steps'
					title: 'guides.build'
					items: [
						Item{'guides.s1.t', 'guides.s1.b', 'git clone https://github.com/metif12/vlip\ncd vlip\n\nv -cc gcc -o vlip.exe vlip.v\n.\\vlip.exe examples\\01_basics.lip'},
						Item{'guides.s2.t', 'guides.s2.b', '(define (square n) (* n n))\n\n(map square [1 2 3 4])   ;=> (1 4 9 16)'},
						Item{'guides.s3.t', 'guides.s3.b', '(define (fizzbuzz n)\n  (cond [(= 0 (mod n 15)) "FizzBuzz"]\n        [(= 0 (mod n 3))  "Fizz"]\n        [(= 0 (mod n 5))  "Buzz"]\n        [else n]))\n\n(map fizzbuzz (range 1 16))'},
						Item{'guides.s4.t', 'guides.s4.b', '(define (fold-left f init xs)\n  (if (null? xs)\n      init\n      (fold-left f (f init (car xs)) (cdr xs))))\n\n(fold-left + 0 [1 2 3 4 5])   ;=> 15'},
						Item{'guides.s5.t', 'guides.s5.b', '; a sum loop needs no stack at all\n(define (sum-to n)\n  (loop i 0 (<= i n)\n    (set! n (- n i))))\n\n(sum-to 1000000)   ; runs in constant space'},
					]
				},
				Section{
					kind: 'prose'
					title: 'guides.nextTitle'
					body: ['guides.next1', 'guides.next2']
				},
				Section{
					kind: 'callout'
					tone: 'note'
					title: 'guides.helpTitle'
					body:  ['guides.help1']
				},
			]
		},
	]
}

// ------------------------------------------------------------------ i18n ---

// tr holds one language, remembering which keys it actually defined so a block
// can be marked as untranslated instead of silently half-English.
struct Tr {
	lang  string
	dir   string
	name  string
	defs  map[string]string
	count int
}

fn load_tr(l Lang) Tr {
	path := 'site/i18n/${l.code}.json'
	raw := os.read_file(path) or {
		eprintln('sitegen: cannot read ${path}')
		return Tr{
			lang: l.code
			dir:  l.dir
			name: l.name
			defs: map[string]string{}
		}
	}
	// A flat string map is the shape json2 decodes most predictably, which is
	// why the translations are flat key/value pairs rather than nested objects.
	m := json2.decode[map[string]string](raw, json2.DecoderOptions{}) or {
		eprintln('sitegen: ${path} is not a valid flat string map')
		return Tr{
			lang: l.code
			dir:  l.dir
			name: l.name
			defs: map[string]string{}
		}
	}
	mut n := 0
	for _, _ in m {
		n++
	}
	return Tr{
		lang:  l.code
		dir:   l.dir
		name:  l.name
		defs:  m
		count: n
	}
}

// t resolves a key, falling back to English. `found` says whether this language
// supplied it.
fn (t &Tr) t(key string, found bool) string {
	if key in t.defs {
		return t.defs[key]
	}
	return ''
}

fn (t &Tr) has(key string) bool {
	return key in t.defs
}

// is_key distinguishes a translation key from a literal cell. Table rows mix
// the two: `features.b1` is a name that gets translated, `250,000` is a number
// that must not be looked up. The English file is the authority, so a string it
// defines is a key and anything else is literal.
fn is_key(en Tr, s string) bool {
	return s in en.defs
}

// resolve returns the text for a key plus whether this language defined it.
fn (t &Tr) resolve(key string, en Tr) (string, bool) {
	if key in t.defs {
		return t.defs[key], true
	}
	if key in en.defs {
		return en.defs[key], false
	}
	return key, false
}

// cell renders one table cell, translating it only if it is a key.
fn cell(t Tr, en Tr, s string) string {
	if !is_key(en, s) {
		return esc(s)
	}
	txt, _ := t.resolve(s, en)
	return inline_code(txt)
}

// ------------------------------------------------------------------ html ---

// esc escapes text for HTML. It is the only place raw text becomes markup, so
// keeping it in one function is what stops an unescaped title from becoming an
// injection vector once a translation file is community-contributed.
//
// Byte-wise on purpose. V iterates a string as BYTES, so a rune loop hands back
// one value per UTF-8 byte: Persian came out as the digits 216174216167... and
// the CJK pages would have been just as wrong. Bytes at or above 0x80 are passed
// through untouched, which leaves every UTF-8 sequence intact.
// esc escapes the five characters that matter in HTML text and attributes, byte
// by byte.
//
// BYTES, not runes. The obvious version iterates the string as characters, which
// on V means bytes anyway but reads as if it did not -- and the reason it says so
// here is that a wrong answer looks identical. Reading the generated Persian page
// through a Windows console that cannot represent Persian shows every non-ASCII
// character as `?`, which is indistinguishable from a generator that mangled it.
// Two of those were chased before the bytes were dumped and found correct. esc
// appends the byte it was given, always; no branch produces a `?`.
fn esc(s string) string {	mut out := []u8{}
	bs := s.bytes()
	mut i := 0
	for i < bs.len {
		c := bs[i]
		if c == u8(`&`) {
			out << "&amp;".bytes()
		} else if c == u8(`<`) {
			out << "&lt;".bytes()
		} else if c == u8(`>`) {
			out << "&gt;".bytes()
		} else if c == u8(`"`) {
			out << "&quot;".bytes()
		} else if c == 39 {
			out << "&#39;".bytes()
		} else {
			out << c
		}
		i++
	}
	return out.bytestr()
}

// A page sits at <lang>/<url>, with English at the root and every other
// language under its own code. That gives two different relative bases, and
// conflating them is how a nav link ends up at /fa/fa/features/:
//
//   self_base -- back to the top of THIS language's directory. Same-language
//                links only, so they never need a language prefix.
//   root_base -- back to the site root. Needed for assets, and for the
//                language switcher, which crosses languages and therefore
//                crosses the prefix.
// up is the relative path from a page back to the site root.
//
// At depth 0 it returns './' rather than ''. An empty base produced href="" on
// the English root -- for the brand link, for every nav item and for the current
// language in the switcher. Browsers resolve href="" to the current URL, so it
// looked right; but it is not a URL, it is nothing, and hreflang links want
// something a crawler can resolve.
fn up(n int) string {
	mut s := ''
	for _ in 0 .. n {
		s += '../'
	}
	return s + './'
}

fn self_base(p Page) string {
	return up(p.depth)
}

fn root_base(t Tr, p Page) string {
	off := if t.lang == 'en' { 0 } else { 1 }
	return up(p.depth + off)
}

// lang_href is the relative URL of page q in language l, as seen from the
// current page.
fn lang_href(t Tr, p Page, l Lang, q Page) string {
	target := if l.code == 'en' { q.url } else { '${l.code}/${q.url}' }
	return root_base(t, p) + target
}

fn page_path(lang string, p Page) string {
	// English lives at the root; every other language under its own code.
	mut d := ''
	if lang != 'en' {
		d = '${lang}/'
	}
	return d + p.url
}

fn page_dir(lang string, p Page) string {
	d := page_path(lang, p)
	if d == '' {
		return ''
	}
	return d.trim_right('/')
}

fn render_head(t Tr, p Page, en Tr, title string, desc string) string {
	base := root_base(t, p)
	lang_attr := if t.lang == 'en' { 'en' } else { t.lang }
	mut s := '<!doctype html>\n'
	s += '<html lang="${lang_attr}" dir="${t.dir}">\n<head>\n'
	s += '<meta charset="utf-8">\n'
	s += '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
	s += '<title>${esc(title)}</title>\n'
	s += '<meta name="description" content="${esc(desc)}">\n'
	s += '<link rel="stylesheet" href="${base}assets/style.css">\n'
	// Alternate links: this is what makes the language switcher crawlable and
	// what lets a search engine index all sixteen.
	//
	// ABSOLUTE URLs, not the page's own relative base. The hreflang attribute is
	// specifically for telling a crawler where the same content lives in another
	// language, and a relative URL resolved against a different page means
	// something different on every one of the sixty-four. Relative paths are right
	// for navigation and wrong here, so this is the one place the site needs to
	// know its own address.
	for l in langs() {
		s += '<link rel="alternate" hreflang="${l.code}" href="${site_url(l, p)}">\n'
	}
	s += '<link rel="alternate" hreflang="x-default" href="${site_url(langs()[0], p)}">\n'
	s += '</head>\n'
	s += render_nav(t, p, en)
	return s
}

// site_url is the absolute address of page p in language l.
//
// Kept next to the generator rather than configured, because a generated site
// with a wrong absolute URL is worse than one with a wrong relative one: the
// relative ones break visibly on click, the absolute ones are just wrong in a
// search index where nobody looks.
fn site_url(l Lang, p Page) string {
	target := if l.code == 'en' { p.url } else { '${l.code}/${p.url}' }
	return site_root + '/' + target
}

fn render_nav(t Tr, p Page, en Tr) string {
	base := self_base(p)
	mut s := '<header class="nav"><div class="navin">\n'
	s += '<a class="brand" href="${base}">v<span>lip</span></a>\n'
	s += '<nav class="links">\n'
	for q in pages() {
		lbl, _ := t.resolve(q.nav, en)
		href := if q.id == p.id { '#' } else { base + q.url }
		cls := if q.id == p.id { ' class="on"' } else { '' }
		s += '<a${cls} href="${href}">${esc(lbl)}</a>\n'
	}
	s += '</nav>\n'
	s += render_lang_switch(t, p, en)
	s += '</div></header>\n'
	return s
}

fn render_lang_switch(t Tr, p Page, en Tr) string {
	base := root_base(t, p)
	mut s := '<div class="langs">\n<button class="langbtn" aria-haspopup="true" aria-expanded="false">'
	lbl, _ := t.resolve('ui.language', en)
	cur := t.name
	s += '${esc(cur)} <span aria-hidden="true">&#9662;</span></button>\n'
	s += '<div class="langmenu" hidden aria-label="${esc(lbl)}">\n'
	for l in langs() {
		// Each language names itself in its own script; that is what a reader
		// scanning the list is actually looking for.
		name := if l.code == t.lang { cur } else { l.name }
		href := lang_href(t, p, l, p)
		cls := if l.code == t.lang { ' class="on"' } else { '' }
		s += '<a${cls} href="${href}" hreflang="${l.code}" lang="${l.code}">${esc(name)}</a>\n'
	}
	s += '</div>\n</div>\n'
	return s
}

// ---------------------------------------------------------------- blocks ---

fn h2(t Tr, en Tr, key string, id string) string {
	txt, _ := t.resolve(key, en)
	return '<h2 id="${id}">${esc(txt)}</h2>\n'
}

// section_missing reports whether any key in the section is untranslated, so the
// block can be labelled rather than passed off as fully localised.
fn section_missing(t Tr, en Tr, s Section) bool {
	if t.lang == 'en' {
		return false
	}
	mut keys := []string{}
	if s.title != '' {
		keys << s.title
	}
	if s.sub != '' {
		keys << s.sub
	}
	keys << s.body
	for it in s.items {
		keys << it.title
		keys << it.body
	}
	keys << s.cols
	for r in s.rows {
		for c in r {
			// Literals are not translation gaps.
			if is_key(en, c) {
				keys << c
			}
		}
	}
	for k in keys {
		if !t.has(k) {
			return true
		}
	}
	return false
}

fn render_section(t Tr, en Tr, s Section, missing bool) string {
	mut o := '<section class="sec">\n'
	if missing {
		mnote, _ := t.resolve('ui.untranslated', en)
		o += '<p class="untrans">${esc(mnote)}</p>\n'
	}
	match s.kind {
		'hero' {
			title, _ := t.resolve(s.title, en)
			sub, _ := t.resolve(s.sub, en)
			o += '<h1>${esc(title)}</h1>\n'
			o += '<p class="lead">${esc(sub)}</p>\n'
			cta, _ := t.resolve('ui.tryIt', en)
			gh, _ := t.resolve('ui.source', en)
			o += '<p class="cta"><a class="btn" href="docs/">${esc(cta)}</a>'
			o += ' <a class="btn ghost" href="https://github.com/metif12/vlip">${esc(gh)}</a></p>\n'
		}
		'cards' {
			o += h2(t, en, s.title, s.kind + '-t')
			o += '<div class="cards">\n'
			for it in s.items {
				ti, _ := t.resolve(it.title, en)
				bo, _ := t.resolve(it.body, en)
				o += '<div class="card"><h3>${esc(ti)}</h3><p>${esc(bo)}</p></div>\n'
			}
			o += '</div>\n'
		}
		'code' {
			ti, _ := t.resolve(s.title, en)
			o += h2(t, en, s.title, 'code')
			o += '<pre><code>${esc(s.code)}</code></pre>\n'
			_ = ti
		}
		'prose' {
			o += h2(t, en, s.title, 'prose')
			for b in s.body {
				txt, _ := t.resolve(b, en)
				o += '<p>${esc(txt)}</p>\n'
			}
		}
		'steps' {
			o += h2(t, en, s.title, 'steps')
			o += '<ol class="steps">\n'
			mut n := 0
			for it in s.items {
				n++
				ti, _ := t.resolve(it.title, en)
				bo, _ := t.resolve(it.body, en)
				o += '<li><h3>${esc(ti)}</h3><p>${esc(bo)}</p>\n'
				if it.code != '' {
					o += '<pre><code>${esc(it.code)}</code></pre>\n'
				}
				o += '</li>\n'
			}
			o += '</ol>\n'
		}
		'table' {
			o += h2(t, en, s.title, 'table')
			o += '<div class="tw"><table>\n<thead><tr>'
			for c in s.cols {
				ct, _ := t.resolve(c, en)
				o += '<th>${esc(ct)}</th>'
			}
			o += '</tr></thead>\n<tbody>\n'
			for r in s.rows {
				o += '<tr>'
				for c in r {
					// A cell that looks like inline code should not be escaped
					// into visible backticks.
					o += '<td>${cell(t, en, c)}</td>'
				}
				o += '</tr>\n'
			}
			o += '</tbody></table></div>\n'
		}
		'callout' {
			ti, _ := t.resolve(s.title, en)
			o += '<div class="callout ${s.tone}">\n'
			o += '<h3>${esc(ti)}</h3>\n'
			for b in s.body {
				txt, _ := t.resolve(b, en)
				o += '<p>${esc(txt)}</p>\n'
			}
			o += '</div>\n'
		}
		else {}
	}
	o += '</section>\n'
	return o
}

// inline_code turns `x` into <code>x</code> and escapes the rest. Documentation
// tables are full of symbol names and reading them as prose is miserable.
fn inline_code(s string) string {
	parts := s.split('`')
	mut o := ''
	for i, part in parts {
		if i % 2 == 1 {
			o += '<code>${esc(part)}</code>'
		} else if part != '' {
			o += esc(part)
		}
	}
	return o
}

fn render_page(t Tr, p Page, en Tr, repo string) string {
	page_title, _ := t.resolve('site.name', en)
	sect_title, _ := t.resolve(p.nav, en)
	title := if p.id == 'home' {
		'${page_title} — ${sect_title}'
	} else {
		'${sect_title} — ${page_title}'
	}
	desc, _ := t.resolve('site.desc', en)
	mut s := render_head(t, p, en, title, desc)
	s += '<main class="wrap">\n'
	if p.depth > 0 {
		mut crumbs := ''
		home_lbl, _ := t.resolve('nav.home', en)
		crumbs = '<a href="${self_base(p)}">${esc(home_lbl)}</a> / <span>${esc(sect_title)}</span>'
		s += '<p class="crumbs">${crumbs}</p>\n'
	}
	for sec in p.secs {
		s += render_section(t, en, sec, section_missing(t, en, sec))
	}
	s += '</main>\n'
	foot, _ := t.resolve('ui.footer', en)
	docs_lbl, _ := t.resolve('nav.docs', en)
	plan_lbl, _ := t.resolve('nav.guides', en)
	s += '<footer class="foot"><div class="wrap">\n'
	s += '<p>${esc(foot)}</p>\n'
	s += '<p class="flinks"><a href="${repo}/blob/main/docs/000-vlip-design.md">docs/000-vlip-design.md</a>'
	s += ' &middot; <a href="${repo}/blob/main/docs/010-roadmap.md">docs/010-roadmap.md</a>'
	s += ' &middot; <a href="${repo}">GitHub</a></p>\n'
	s += '<p class="dim">${esc(docs_lbl)} &middot; ${esc(plan_lbl)}</p>\n'
	s += '</div></footer>\n'
	s += '<script src="${root_base(t, p)}assets/site.js" defer></script>\n'
	s += '</body>\n</html>\n'
	return s
}

fn main() {
	repo := 'https://github.com/metif12/vlip'
	out := 'site_out'
	os.rmdir_all(out)
	os.mkdir_all(out) or { panic('sitegen: cannot create ${out}') }

	// English is the fallback, so it is loaded first and every other language is
	// resolved against it.
	all := langs()
	en := load_tr(all[0])
	// pages() builds the slice on every call, so hold one: calling it twice for
	// a count and a loop means building the content twice.
	ps := pages()

	mut stats := []string{}
	mut total_missing := 0
	for i, l in all {
		t := if i == 0 { en } else { load_tr(l) }
		for p in ps {
			dir := '${out}/${page_dir(t.lang, p)}'
			os.mkdir_all(dir) or { panic('sitegen: cannot create ${dir}') }
			html := render_page(t, p, en, repo)
			os.write_file('${dir}/index.html', html) or {
				panic('sitegen: cannot write ${dir}/index.html')
			}
		}
		mut miss := 0
		for p in ps {
			for sec in p.secs {
				if section_missing(t, en, sec) {
					miss++
				}
			}
		}
		total_missing += miss
		note := if i == 0 { 'reference' } else {
			'${t.count} keys, ${miss} untranslated block(s)'
		}
		// Pad by hand: this V has no String.pad, and the column is only here to
		// make the summary readable.
		mut code := l.code
		for _ in 0 .. 3 - code.len {
			code += ' '
		}
		stats << '${code} ${l.dir}  ${note}'
	}

	// A root index that greets in the reader's language is friendlier than
	// silently choosing one, but redirecting surprises people who linked here,
	// so English stays the root and the switcher does the rest.
	os.write_file('${out}/.nojekyll', '') or {}

	println('sitegen: ${all.len} languages x ${ps.len} pages')
	for s in stats {
		println('  ${s}')
	}
	if total_missing > 0 {
		println('${total_missing} block(s) fall back to English and are labelled as such')
	}
}
